[package]
name = "env_and_args"
version = "0.1.0"
authors = ["Raina Pepe <raina.pepe@jbtec.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"

[[bin]]
name = "env_and_args"
path = "main.rs"
