[package]
name = "struct_pointers"
version = "0.1.0"
authors = ["rainapepe <raina.pepe@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="struct_pointers"
path="main.rs"