[package]
name = "impl_add"
version = "0.1.0"
authors = ["rainapepe <raina.pepe@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "impl_add"
path = "main.rs"
