[package]
name = "curry"
version = "0.1.0"
authors = ["Raina Pepe <raina.pepe@jbtec.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "curry"
path = "main.rs"
